[project]
name = "resume-ats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.6.0",
    "datasets>=3.5.0",
<<<<<<< HEAD
    "joblib>=1.4.2",
=======
    "keybert>=0.9.0",
>>>>>>> main
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "torch>=2.6.0",
    "transformers>=4.51.3",
    "uv>=0.6.14",
]
