apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-ingress
  namespace: default
  # No annotations needed for this setup
spec:
  rules:
  - host: localhost
    http:
      paths:
      # API path
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: resume-backend
            port:
              # CHANGE THIS to match the Service port
              number: 5000
      # Frontend path
      - pathType: Prefix
        path: /
        backend:
          service:
            name: resume-frontend
            port:
              number: 80 # Keep this as 80 for the frontend Caddy service
