apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-replica-set
  namespace: default
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram-credentials
    - name: app-user
      db: app
      passwordSecretRef:
        name: mongodb-app-password
      roles:
        - name: readWrite
          db: app
      scramCredentialsSecretName: app-user-scram-credentials
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
  namespace: default
type: Opaque
stringData:
  password: admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-app-password
  namespace: default
type: Opaque
stringData:
  password: app123
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
spec:
  selector:
    app: mongodb-replica-set-svc
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017
  type: NodePort

